export type SkillLevel = 'Beginner' | 'Intermediate' | 'Advanced' | 'Beginner-Intermediate' | 'Intermediate-Advanced' | 'All Levels';
export type Topic = 'Machine Learning' | 'Deep Learning' | 'NLP' | 'Computer Vision' | 'MLOps' | 'Generative AI';
export type Duration = 'Under 5 hours' | '5-10 hours' | '10-20 hours' | '20+ hours';
export type Price = 'Free' | 'Paid' | 'Pro only';

export interface Course {
  id: number;
  title: string;
  instructor: string;
  instructorAvatar: string;
  description: string;
  skillLevel: SkillLevel;
  topic: Topic;
  durationHours: number;
  lessonCount: number;
  rating: number;
  reviewCount: number;
  price: number;
  priceType: Price;
  thumbnail: string;
  isPopular?: boolean;
}

export const coursesData: Course[] = [
  {
    id: 1,
    title: 'Machine Learning A-Z: From Fundamentals to Production',
    instructor: 'Dr. Sarah Chen',
    instructorAvatar: 'SC',
    description: 'Complete machine learning course covering theory, practical applications, and deployment strategies for real-world scenarios.',
    skillLevel: 'Beginner-Intermediate',
    topic: 'Machine Learning',
    durationHours: 12,
    lessonCount: 45,
    rating: 4.8,
    reviewCount: 2300,
    price: 49,
    priceType: 'Paid',
    thumbnail: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg',
    isPopular: true,
  },
  {
    id: 2,
    title: 'Deep Learning with PyTorch',
    instructor: 'James Wilson',
    instructorAvatar: 'JW',
    description: 'Master deep learning frameworks and build neural networks from scratch using PyTorch for cutting-edge AI applications.',
    skillLevel: 'Intermediate',
    topic: 'Deep Learning',
    durationHours: 18,
    lessonCount: 62,
    rating: 4.9,
    reviewCount: 1800,
    price: 49,
    priceType: 'Paid',
    thumbnail: 'https://images.pexels.com/photos/8438922/pexels-photo-8438922.jpeg',
    isPopular: true,
  },
  {
    id: 3,
    title: 'Natural Language Processing Masterclass',
    instructor: 'Dr. Priya Sharma',
    instructorAvatar: 'PS',
    description: 'Advanced NLP techniques including transformers, sentiment analysis, and language model fine-tuning for production systems.',
    skillLevel: 'Advanced',
    topic: 'NLP',
    durationHours: 24,
    lessonCount: 78,
    rating: 4.7,
    reviewCount: 1200,
    price: 49,
    priceType: 'Paid',
    thumbnail: 'https://images.pexels.com/photos/8438918/pexels-photo-8438918.jpeg',
  },
  {
    id: 4,
    title: 'Computer Vision from Scratch',
    instructor: 'Alex Rodriguez',
    instructorAvatar: 'AR',
    description: 'Learn image processing, object detection, and computer vision algorithms with hands-on projects and real applications.',
    skillLevel: 'Intermediate',
    topic: 'Computer Vision',
    durationHours: 15,
    lessonCount: 52,
    rating: 4.8,
    reviewCount: 980,
    price: 49,
    priceType: 'Paid',
    thumbnail: 'https://images.pexels.com/photos/8386434/pexels-photo-8386434.jpeg',
  },
  {
    id: 5,
    title: 'Generative AI & Large Language Models',
    instructor: 'Dr. Michael Chang',
    instructorAvatar: 'MC',
    description: 'Explore GPT, DALL-E, and other generative models. Build AI applications that create content and solve complex problems.',
    skillLevel: 'Intermediate-Advanced',
    topic: 'Generative AI',
    durationHours: 20,
    lessonCount: 68,
    rating: 4.9,
    reviewCount: 2100,
    price: 49,
    priceType: 'Paid',
    thumbnail: 'https://images.pexels.com/photos/8439093/pexels-photo-8439093.jpeg',
    isPopular: true,
  },
  {
    id: 6,
    title: 'MLOps: Deploying ML Models to Production',
    instructor: 'Emma Thompson',
    instructorAvatar: 'ET',
    description: 'Master the art of deploying, monitoring, and maintaining machine learning models in production environments.',
    skillLevel: 'Advanced',
    topic: 'MLOps',
    durationHours: 16,
    lessonCount: 48,
    rating: 4.7,
    reviewCount: 756,
    price: 49,
    priceType: 'Paid',
    thumbnail: 'https://images.pexels.com/photos/8438991/pexels-photo-8438991.jpeg',
  },
  {
    id: 7,
    title: 'Python for Data Science & Machine Learning',
    instructor: 'Robert Kim',
    instructorAvatar: 'RK',
    description: 'Start your data science journey with Python. Learn pandas, numpy, scikit-learn, and visualization libraries from scratch.',
    skillLevel: 'Beginner',
    topic: 'Machine Learning',
    durationHours: 10,
    lessonCount: 38,
    rating: 4.8,
    reviewCount: 3200,
    price: 0,
    priceType: 'Free',
    thumbnail: 'https://images.pexels.com/photos/8386422/pexels-photo-8386422.jpeg',
    isPopular: true,
  },
  {
    id: 8,
    title: 'Neural Networks Fundamentals',
    instructor: 'Dr. Lisa Anderson',
    instructorAvatar: 'LA',
    description: 'Understand the mathematics and theory behind neural networks. Build networks from scratch and optimize performance.',
    skillLevel: 'Beginner-Intermediate',
    topic: 'Deep Learning',
    durationHours: 8,
    lessonCount: 32,
    rating: 4.9,
    reviewCount: 1500,
    price: 49,
    priceType: 'Paid',
    thumbnail: 'https://images.pexels.com/photos/8439089/pexels-photo-8439089.jpeg',
  },
  {
    id: 9,
    title: 'Reinforcement Learning in Practice',
    instructor: 'David Martinez',
    instructorAvatar: 'DM',
    description: 'Advanced reinforcement learning techniques for game AI, robotics, and autonomous systems with practical implementations.',
    skillLevel: 'Advanced',
    topic: 'Machine Learning',
    durationHours: 22,
    lessonCount: 72,
    rating: 4.6,
    reviewCount: 542,
    price: 49,
    priceType: 'Paid',
    thumbnail: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg',
  },
  {
    id: 10,
    title: 'AI for Image Generation and Editing',
    instructor: 'Sophie Laurent',
    instructorAvatar: 'SL',
    description: 'Create stunning images with AI. Master diffusion models, style transfer, and advanced image manipulation techniques.',
    skillLevel: 'Intermediate',
    topic: 'Generative AI',
    durationHours: 14,
    lessonCount: 46,
    rating: 4.8,
    reviewCount: 1100,
    price: 49,
    priceType: 'Paid',
    thumbnail: 'https://images.pexels.com/photos/8438993/pexels-photo-8438993.jpeg',
  },
  {
    id: 11,
    title: 'Conversational AI and Chatbots',
    instructor: 'Marcus Johnson',
    instructorAvatar: 'MJ',
    description: 'Build intelligent chatbots and conversational AI systems using modern NLP techniques and dialogue management.',
    skillLevel: 'Intermediate',
    topic: 'NLP',
    durationHours: 11,
    lessonCount: 40,
    rating: 4.7,
    reviewCount: 890,
    price: 49,
    priceType: 'Paid',
    thumbnail: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg',
  },
  {
    id: 12,
    title: 'Object Detection and Tracking Systems',
    instructor: 'Dr. Nina Patel',
    instructorAvatar: 'NP',
    description: 'Advanced computer vision for real-time object detection, tracking, and recognition in video streams and images.',
    skillLevel: 'Advanced',
    topic: 'Computer Vision',
    durationHours: 19,
    lessonCount: 58,
    rating: 4.8,
    reviewCount: 720,
    price: 49,
    priceType: 'Paid',
    thumbnail: 'https://images.pexels.com/photos/8438918/pexels-photo-8438918.jpeg',
  },
];

export const skillLevels: SkillLevel[] = ['Beginner', 'Intermediate', 'Advanced', 'All Levels'];
export const topics: Topic[] = ['Machine Learning', 'Deep Learning', 'NLP', 'Computer Vision', 'MLOps', 'Generative AI'];
export const durations: Duration[] = ['Under 5 hours', '5-10 hours', '10-20 hours', '20+ hours'];
export const priceTypes: Price[] = ['Free', 'Paid', 'Pro only'];
